### ISSUE TITLE
Segfault on chunks screen

### ISSUE THREAD

**Issue by louipc** [louipc/tremc#1]
Viewing the chunks screen can sometimes cause the program to segfault.
This is most likely a flaw in a python module.
When it happens its repeatable on the torrent it occurs on.

**Comment by louipc** [comment]
Bug doesn't show up when using pudb
https://github.com/fagga/transmission-remote-cli/issues/117#issuecomment-168401300

**Comment by troxor** [comment]
Do you have any example torrents where this occurs? I tried the latest Archlinux magnet link to test -> magnet:?xt=urn:btih:947ab012bd1bf11f4f1d29f8fa1eab73a85fe793&dn=archlinux-2016.11.01-dual.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce

**Comment by louipc** [comment]
On Wed 02 Nov 2016 13:23 -0700, Troy C. wrote:
> Do you have any example torrents where this occurs? I tried the latest
> Archlinux magnet link to test

I actually don't have any currently but when I recently rebased my patches on
top of the original project I noticed the segfault still occurred. Probably
should have saved them for debugging. I'll keep the issue open for awhile though.

**Comment by louipc** [comment]
On Wed 02 Nov 2016 13:23 -0700, Troy C. wrote:
> Do you have any example torrents where this occurs?

I actually reproduced the segfault right now.

My torrents are:
ArchStrike-openbox-2016.07.21-x86_64.iso
blackarchlinux-live-2016.08.31-x86_64.iso
Qubes-R3.2-x86_64
tails-i386-2.6
archlinux-2016.11.01-dual.iso

I don't think torrents matter in this case.
What matters is that after you launch tremc only move the cursor *down*
(no other action/keystroke) then <enter> to open details, then move over to
chunks screen. (either with cursor or by hitting 'c')

I tried 20 times and I got 10 segfaults.
The segfault seems about 50% repeatable like this.

If you get a session that doesn't segfault on first try then it seems that it
won't segfault for the rest of the time that the program is open.

**Comment by troxor** [comment]
I loaded up the same list of torrents there (and a couple others), and went through the same actions about 20 times, but didn't encounter a segfault. What version of Python are you using? There were a lot of these during my initial "port" to python3, and I suspect there are some edge cases that I never encountered, specifically when a torrent has errors, trackers can't be reached, etc.

**Comment by louipc** [comment]
On Thu 03 Nov 2016 08:30 -0700, Troy C. wrote:
> I loaded up the same list of torrents there (and a couple others), and went
> through the same actions about 20 times, but didn't encounter a segfault. What
> version of Python are you using?

I'm glad you're not experiencing segfaults.
I have python version 3.5.2. The way the environment is set up may have
something to do with it. The last time I played with it months ago the segfaults
would not occur via pudb. It's definitely something worth investigating.
I don't currently have the ability to tackle it, but will try to over time.

> There were a lot of these during my initial "port" to python3, and I suspect
> there are some edge cases that I never encountered, specifically when
> a torrent has errors, trackers can't be reached, etc.

There might be some conditions that I haven't tested that should show up as
interpreter errors that would halt the program. As I understand they shouldn't
crash the interpreter itself unless it (or some module) has a flaw.

I just tested via pudb again and sure enough I was able to segfault the whole
session a few times. That requires restarting pudb for each attempt. If it
doesn't segfault the first time, then you can restart tremc within pudb and the
segfault won't occur. Definitely has something to do with the state of the
python interpreter. Improperly handled memory, race condition, something...

**Comment by louipc** [comment]
I was trying to debug this awhile ago and it seemed to be caused by colour handling in pythons ncurses bindings or something. But after updating python this bug completely disappeared. So closing for now.
