### ISSUE TITLE
Crash on torrent add

### ISSUE THREAD

**Issue by nnnn20430** [louipc/tremc#11]
this is a bug i started having with transmission-remote-cli quite a while ago
and now testing tremc it seems it still has this bug so i decided to make a report

when i press "a" on my keyboard to add a torrent tremc instantly crashes with the following error:

```
Traceback (most recent call last):
  File "./tremc", line 3710, in <module>
    Interface()
  File "./tremc", line 982, in __init__
    self.run()
  File "./tremc", line 1091, in run
    self.handle_user_input()
  File "./tremc", line 1783, in handle_user_input
    f(c)
  File "./tremc", line 1158, in a_key
    self.add_torrent()
  File "./tremc", line 1220, in add_torrent
    free_space = float(server.get_free_space())/(10**9) # Bytes > GB
  File "./tremc", line 552, in get_free_space
    free = response['arguments']['size-bytes']
KeyError: 'size-bytes'
```

i did some debugging it seems it's because i run transmission-daemon with a relative download dir, and the "free-space" request returns result "directory path is not absolute".

i think as a workaround get_free_space should just return 0
```
request = TransmissionRequest(self.host, self.port, self.path, 'free-space', 1, {'path': dir})
request.send_request()
response = request.get_response()
if 'size-bytes' in response['arguments']:
    free = response['arguments']['size-bytes']
else:
    free = 0
```

**Comment by louipc** [comment]
On Thu 30 Nov 2017 13:30 +0000, N Nullbuilt, version 20430 wrote:
> this is a bug i started having with transmission-remote-cli quite a while ago
> and now testing tremc it seems it still has this bug so i decided to make a report
> 
> when i press "a" on my keyboard to add a torrent tremc instantly crashes with the following error:
> `
> Traceback (most recent call last):
>   File "./tremc", line 3710, in <module>
>     Interface()
>   File "./tremc", line 982, in __init__
>     self.run()
>   File "./tremc", line 1091, in run
>     self.handle_user_input()
>   File "./tremc", line 1783, in handle_user_input
>     f(c)
>   File "./tremc", line 1158, in a_key
>     self.add_torrent()
>   File "./tremc", line 1220, in add_torrent
>     free_space = float(server.get_free_space())/(10**9) # Bytes > GB
>   File "./tremc", line 552, in get_free_space
>     free = response['arguments']['size-bytes']
> KeyError: 'size-bytes'
> `
>
> i think it may have started happening because i have too many torrents
> i have 685 torrents currently taking up 1.3TB of space

Oh dang. Looks like we're not ready for the terabyte age afterall.

**Comment by nnnn20430** [comment]
@louipc i see you replied using email, i have edited the issue because i decided to debug the problem my self and found that it was something else you should look at the current text on github

**Comment by nnnn20430** [comment]
@louipc btw the files list in details view isn't even ready for the gigabyte age, it assumes text before the file names (index, progress, size, priority) can only be 30 char long and it breaks like this with big files:
```
                               \ some_dir
  1  100.00%  11.36G   normal    | big_file.tar.gz
  2  100.00%   508K   normal    | small_file1.zip
  3  100.00%   1.5M   normal    | small_file2.zip
```

**Comment by louipc** [comment]
On Fri 01 Dec 2017 03:13 -0800, N Nullbuilt, version 20430 wrote:
> @louipc i see you replied using email, i have edited the issue because
> i decided to debug the problem my self and found that it was something else
> you should look at the current text on github 

Thank you for the information. I was wondering why size-bytes was not included
in the response. Would you like to submit a patch for inclusion for the glory?

**Comment by louipc** [comment]
On Fri 01 Dec 2017 06:55 -0800, N Nullbuilt, version 20430 wrote:
> @louipc btw the files list in details view isn't even ready for the gigabyte age, it assumes text before the file names (index, progress, size, priority) can only be 30 char long and it breaks like this with big files:
> ```
>                                \ some_dir
>   1  100.00%  11.36G   normal    | big_file.tar.gz
>   2  100.00%   508K   normal    | small_file1.zip
>   3  100.00%   1.5M   normal    | small_file2.zip
> ```

Please create a new issue for this. Thanks.

**Comment by louipc** [comment]
Assuming fixed since you submitted the patch.
