### ISSUE TITLE
completions

### ISSUE THREAD

**Issue by idanielblake** [louipc/tremc#14]
Hello
The completions are for transmission-remote-cli. Should'nt they rename?
Thank you

**Comment by louipc** [comment]
On Sun 17 Dec 2017 13:31 +0000, idanielblake wrote:
> The completions are for transmission-remote-cli. Should'nt they rename?

Hello idanielblake. Yes you are correct. Thank you for noticing.
Would you like to submit a patch for the credits? Thanks.
