### ISSUE TITLE
Configuring Colour 

### ISSUE THREAD

**Issue by ralpheeee88** [louipc/tremc#9]
is there anyway to choose / configure colours?
https://i.imgur.com/kUOr7fw.png
essentially i am trying to get rid of the background grey colour and just have my default background terminal colour.

**Comment by louipc** [comment]
On Tue 14 Nov 2017 08:48 +0000, Ralpheeee88 wrote:
> is there anyway to choose / configure colours?

Yes there should be a file at $HOME/.config/tremc/settings.cfg
You can configure colours from there.

**Comment by ralpheeee88** [comment]
@louipc think i am missing the obvious so apologise in advance....
https://i.imgur.com/3fUvzRc.png
1) when selecting black i get the dark blueish black colour background
2) i would also like to change the grey colour to black but cant find the corresponding setting 

cfg file: http://ix.io/CgZ

**Comment by louipc** [comment]
On Wed 15 Nov 2017 01:03 +0000, Ralpheeee88 wrote:
> @louipc think i am missing the obvious so apologise in advance....
> https://i.imgur.com/3fUvzRc.png
> 1) when selecting black i get the dark blueish black colour background
> 2) i would also like to change the grey colour to black but cant find the corresponding setting 
> 
> cfg file: http://ix.io/CgZ

Those should just be your terminal background and foreground colours. I dont
think you can set them independently in tremc. I would be willing to accept
a patch for that.
